[params.variables]
color_primary = "#6366f1"
color_secondary = "#4f46e5"
body_color = "#fff"
text_color = "#71717f"
text_dark = "#1d1d22"
text_light = "#a1a1ac"
border_color = "#ececf3"
dark_body_color = "#1E262C"
dark_text_color = "#cbd2da"
dark_text_light = "#9aa4b2"
dark_text_dark = "#fff"
dark_border_color = "#2c3742"
black = "#101418"
white = "#fff"
light = "#f6f6fb"
dark = "#232d35"

font_size = "16px"

# "minorSecond": 1.067,
# "majorSecond": 1.125,
# "minorThird": 1.2,
# "majorThird": 1.25,
# "perfectFourth": 1.333,
# "augmentedFourth": 1.414,
# "perfectFifth": 1.5,
# "goldenRatio": 1.618
font_scale = "1.25"

font_primary = "Urbanist:wght@500;600;700"
font_primary_type = "sans-serif"
font_secondary = "Poppins:wght@400;500"
font_secondary_type = "sans-serif"
font_icon = "Font Awesome 6 Free"

# CSS Plugins
[[params.plugins.css]]
link = "plugins/swiper/swiper-bundle.css"
# [[params.plugins.css]]
# link = "plugins/glightbox/glightbox.css"

# JS Plugins
[[params.plugins.js]]
link = "plugins/swiper/swiper-bundle.js"
[[params.plugins.js]]
link = "plugins/cookie.js"
[[params.plugins.js]]
link = "plugins/lazy-loader.js"
[[params.plugins.js]]
link = "js/tab.js"
# [[params.plugins.js]]
# link = "plugins/glightbox/glightbox.js"
# [[params.plugins.js]]
# link = "js/gallery-slider.js"
